# Nixpacks configuration for Railway deployment
providers = ["node"]

[phases.install]
cmds = [
  "node -v",
  "npm -v",
  "npm ci --no-audit --no-fund --verbose"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_LOGLEVEL = "verbose"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"